apiVersion: v1
kind: Secret
metadata:
  name: typesense-secret
  namespace: fs-search
type: Opaque
data:
  # Base64 encoded API key - replace with your actual key
  # To generate: echo -n "your-secure-api-key" | base64
  # TYPESENSE_API_KEY: <base64-encoded-value-here>
stringData:
  # For development - use stringData for plain text
  # TYPESENSE_API_KEY: "your-secure-api-key-here"