apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  namespace: fs-search
  labels:
    app: typesense
spec:
  serviceName: typesense-headless
  replicas: 3  # For HA setup, use 1 for single node
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
    spec:
      containers:
      - name: typesense
        image: typesense/typesense:0.25.0
        ports:
        - name: api
          containerPort: 8108
          protocol: TCP
        - name: peering
          containerPort: 8107
          protocol: TCP
        env:
        - name: TYPESENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: typesense-secret
              key: TYPESENSE_API_KEY
        - name: TYPESENSE_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: typesense-config
              key: TYPESENSE_DATA_DIR
        - name: TYPESENSE_API_PORT
          valueFrom:
            configMapKeyRef:
              name: typesense-config
              key: TYPESENSE_API_PORT
        - name: TYPESENSE_PEERING_PORT
          valueFrom:
            configMapKeyRef:
              name: typesense-config
              key: TYPESENSE_PEERING_PORT
        - name: TYPESENSE_ENABLE_CORS
          valueFrom:
            configMapKeyRef:
              name: typesense-config
              key: TYPESENSE_ENABLE_CORS
        - name: TYPESENSE_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: typesense-config
              key: TYPESENSE_LOG_LEVEL
        # For multi-node cluster setup
        - name: TYPESENSE_NODES
          value: "typesense-0.typesense-headless.fs-search.svc.cluster.local:8107,typesense-1.typesense-headless.fs-search.svc.cluster.local:8107,typesense-2.typesense-headless.fs-search.svc.cluster.local:8107"
        command:
        - /opt/typesense-server
        args:
        - --data-dir=$(TYPESENSE_DATA_DIR)
        - --api-key=$(TYPESENSE_API_KEY)
        - --api-port=$(TYPESENSE_API_PORT)
        - --peering-port=$(TYPESENSE_PEERING_PORT)
        - --nodes=$(TYPESENSE_NODES)
        - --enable-cors
        - --log-level=$(TYPESENSE_LOG_LEVEL)
        volumeMounts:
        - name: typesense-data
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8108
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8108
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8108
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
  volumeClaimTemplates:
  - metadata:
      name: typesense-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 10Gi